services:
  app:
    build: .
    # 设置环境变量
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql:5432/vevss_db
    # 映射 8080 端口
    ports:
      - "8081:8080"
    # 依赖mysql和redis服务
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
  # nginx服务配置
  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      # 挂载 配置文件 和 静态资源
      - ./init/react.conf:/etc/nginx/conf.d/react.conf
      - ./build:/usr/share/nginx/html

# PostgreSQL
  postgresql:
    image: postgres:16
    environment:
        POSTGRES_USER: "vevss"
        POSTGRES_PASSWORD: "!Qwer432"
        POSTGRES_DB: "vevss_db"
        LANG: en_US.UTF-8
        TZ: Asia/Shanghai
    volumes:
        - ./init:/docker-entrypoint-initdb.d
    expose:
      - 5432
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "vevss" ]
        interval: 10s
        timeout: 5s
        retries: 5

  # redis服务配置
  redis:
    image: redis:7.2.3
    command: [ "redis-server", "--requirepass", "qweasdzxc" ]
    expose:
      - 6379