services:
  app:
    build: .
    # 设置环境变量
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql:5432/vevss
    # 映射 8080 端口
    ports:
      - "8080:8080"
    # 依赖mysql和redis服务
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started

# PostgreSQL
  postgresql:
    image: postgres:16
    environment:
        POSTGRES_USER: vevss
        POSTGRES_PASSWORD: "!Qwer432"
        POSTGRES_DB: vevss
    volumes:
        - ./init/db.sql:/docker-entrypoint-initdb.d/db.sql
    expose:
      - 5432
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "vevss" ]
        interval: 10s
        timeout: 5s
        retries: 5

  # redis服务配置
  redis:
    image: redis:7.2.3
    command: [ "redis-server", "--requirepass", "qweasdzxc" ]
    expose:
      - 6379