server:
  port: 8080
spring:
  cache:
    type: redis
    cache-names: vevss
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      timeout: 3000
      password: qweasdzxc

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    #    124.70.27.30:15400
    url: jdbc:postgresql://postgresql:5432/vevss
    username: vevss
    password: '!Qwer432'
    driver-class-name: org.postgresql.Driver

logging:
  config: classpath:log4j2.xml
  level:
    root: info